[project]
name = "imgtools"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "bs4>=0.0.2",
    "click>=8.1.8",
    "more-itertools>=10.6.0",
    "pillow>=11.1.0",
    "pyserial>=3.5",
]

[project.scripts]
imgtools = "imgtools:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"