[ipx]
ipx=true

[autoexec]
MOUNT C .
c:
ipxnet startserver 33213
set mtcpcfg=mtcpsvr.cfg
#ipxnet connect 127.0.0.1 33213
#ipxnet status
#ipxpkt 0x60
#nc -target 192.168.8.2 7000 -bin -verbose < ipxpkt.com
jrecv -port 7000 > test.txt